const path = require("path");
const nodeExternals = require("webpack-node-externals");

module.exports = {
  entry: "./src/index.ts",
  target: "web",
  devtool: "source-map",
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: "ts-loader",
        exclude: /node_modules/,
      },
      {
        test: /\.css$/,
        exclude: /node_modules/,
        use: [
          "style-loader",
          {
            loader: "@teamsupercell/typings-for-css-modules-loader",
            options: {
              banner:
                "/** autogenerated by typings-for-css-modules-loader. **/ \n// Please do not change this file!",
            },
          },
          {
            loader: "css-loader",
            options: {
              modules: true,
              import: true,
            },
          },
        ],
      },
    ],
  },
  resolve: {
    extensions: [".tsx", ".ts", ".js", ".css"],
  },
  output: {
    filename: "leaflet-velocity.js",
    path: path.resolve(__dirname, "dist"),
    library: {
      name: "leafletVelocity",
      type: "umd",
      export: "default",
    },
    globalObject: "this",
  },
  externals: [nodeExternals()],
};
